apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bluefin-api-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: bluefin-dev
  system: bluefin
  definition: |
    openapi: 3.0.1
    paths:
      /greeting:
        get:
          operationId: greeting
          parameters:
          - in: query
            name: name
            required: false
            schema:
              default: World
              description: OK
          tags:
          - greeting-controller
    servers:
    - url: https://bluefin-api.default.skynetsystems.io

