apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bluefin-api-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: experimental 
  owner: bluefin-dev
  system: bluefin
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
