apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bluefin-dev
  description: bluefin-dev 
spec:
  type: sub-department
  profile:
    displayName: bluefin-dev
    email: bluefin-dev@fiserv.com
    picture: https://raw.githubusercontent.com/pivotal-ben-chacko/fiserv/main/resources/office-building-fiserv.png 
  parent: it
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jacob
spec:
  profile:
    displayName: Jacob Vaidyan
    email: jacob.vaidyan@fiserv.com
    picture: https://raw.githubusercontent.com/pivotal-ben-chacko/fiserv/main/resources/knight-fiserv.png 
  memberOf: [bluefin-dev]
