apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DevOps
  description: The IT department
spec:
  type: department
  # Intentional no profile for testing
  parent: fiserv
  children: [bluefin-dev]
